/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CleanCalculator;

public class App {
  public static void main(String[] args) {
    CommandLineReader commandLineReader = new JavaUtilCommandLineReader();
    FileReader fileReader = new JavaUtilFileReader();
    FileParser<int[]> fileParser = new IntegerFileParser();
    Calculator calculator = new BasicCalculator();
    Printer printer = new JavaUtilPrinter();
    CalculatorLogger calculatorLogger = null;

    CleanCalculator cleanCalculator = new MyCleanCalculator(
        commandLineReader,
        fileReader,
        fileParser,
        calculator,
        printer,
        calculatorLogger);

    cleanCalculator.makeArithmeticOperationOnFile(null, null);
  }
}
