/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CleanCalculator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Random;
import java.util.Scanner;

class AppTest {
  
    @Test void appHasAGreeting() {
        
    }
}
